mkdir "New Tickets"
mkdir "Completed Tickets"
mkdir "\Completed Tickets\Pictures"
start "\Windows\wceload.exe" "\Flash Disk\Start\HardReset\CartLogic\Install SQL\sqlce.wce5.armv4i.CAB"
start "\Windows\wceload.exe" "\Flash Disk\Start\HardReset\CartLogic\Install SQL\sqlce.dev.ENU.wce5.armv4i.CAB"
start "\Windows\wceload.exe" "\Flash Disk\Start\HardReset\CartLogic\Install SQL\NETCFv35.Messages.EN.cab"